export * as baseApi from './base.api'

// /** System */
export * as clientApi from './sys/client.api'
export * as deptApi from './sys/dept.api'
export * as configApi from './sys/config.api'
export * as dictApi from './sys/dict.api'
export * as userApi from './sys/user.api'
export * as menuApi from './sys/menu.api'
export * as noticeApi from './sys/notice.api'
export * as ossApi from './sys/oss.api'
export * as roleApi from './sys/role.api'
export * as postApi from './sys/post.api'
export * as tenantApi from './sys/tenant.api'
export * as tenantPackageApi from './sys/tenant-package.api'
