/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseLayout: typeof import('./layouts/BaseLayout.vue')['default']
    BlankLayout: typeof import('./layouts/BlankLayout.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    LayoutActions: typeof import('./layouts/_views/LayoutActions.vue')['default']
    LayoutMenu: typeof import('./layouts/_views/LayoutMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
    VAsidePage: typeof import('./pages/_views/VAsidePage.vue')['default']
    VCard: typeof import('./pages/_views/VCard.vue')['default']
    VDictTag: typeof import('./pages/_views/VDictTag.vue')['default']
    VPage: typeof import('./pages/_views/VPage.vue')['default']
    VTabPage: typeof import('./pages/_views/VTabPage.vue')['default']
    ZeActions: typeof import('./components/ZeActions.vue')['default']
    ZeForm: typeof import('./components/ZeForm.vue')['default']
    ZeFormItem: typeof import('./components/ZeFormItem.vue')['default']
    ZeInput: typeof import('./components/ZeInput.vue')['default']
    ZeModal: typeof import('./components/ZeModal.vue')['default']
    ZePagination: typeof import('./components/ZePagination.vue')['default']
    ZeTable: typeof import('./components/ZeTable.vue')['default']
    ZeTableColumn: typeof import('./components/ZeTableColumn.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
